services:
  app:
    build:
      context: .
    container_name: simple-crud-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/shared/app

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./shared:/shared/db
